# Generated by Django 3.0 on 2021-02-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('subject_details', models.TextField()),
                ('address', models.TextField()),
                ('identity_proof', models.FileField(upload_to='id_proof/')),
                ('qualification_details', models.TextField()),
                ('extra_details', models.TextField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor')),
            ],
        ),
    ]
