# Generated by Django 3.0 on 2021-02-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor'),
            preserve_default=False,
        ),
    ]
