# Generated by Django 3.0 on 2021-03-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210315_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor'),
        ),
    ]
