# Generated by Django 3.0 on 2021-03-16 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210315_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_request',
            name='pstatus',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor'),
        ),
        migrations.AlterField(
            model_name='student_request',
            name='rstatus',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_request',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
        migrations.AlterField(
            model_name='student_request',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor'),
        ),
    ]
