# Generated by Django 3.0 on 2021-03-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_add_student_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_student_batch',
            name='bnum',
        ),
    ]
