# Generated by Django 3.0 on 2021-03-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_add_student_batch_bnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_student_batch',
            name='bnum',
            field=models.CharField(default='', max_length=100),
        ),
    ]
