# Generated by Django 3.0 on 2021-03-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_add_student_batch_bnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_student_batch',
            old_name='Student',
            new_name='student',
        ),
    ]
