# Generated by Django 3.0 on 2021-03-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210317_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_by_tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_doc', models.FileField(upload_to='tutor_doc/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor')),
            ],
        ),
    ]
