# Generated by Django 3.0 on 2021-03-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_upload_by_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_by_tutor',
        ),
    ]
