# Generated by Django 3.0 on 2021-03-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_delete_upload_by_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_by_tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnum', models.CharField(max_length=100)),
                ('filename', models.FileField(upload_to='tutor_doc/')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor')),
            ],
        ),
    ]
