# Generated by Django 3.0 on 2021-03-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_upload_by_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_by_tutor',
            name='bnum',
        ),
    ]
