# Generated by Django 3.0 on 2021-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_upload_by_tutor_bnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_by_tutor',
            name='bnum',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
