# Generated by Django 3.0 on 2021-03-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_upload_by_tutor_bnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content_by_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.FileField(upload_to='student_doc/')),
                ('add_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Add_batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor')),
            ],
        ),
    ]
