# Generated by Django 3.0 on 2021-03-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_content_by_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_by_student',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor'),
        ),
    ]
