# Generated by Django 3.0 on 2021-03-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20210322_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_by_student',
            name='add_batch',
        ),
    ]
