# Generated by Django 3.0 on 2021-03-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_content_by_student_add_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='semail',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
