# Generated by Django 3.0 on 2021-03-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_parent_semail'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='tutor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Tutor'),
        ),
    ]
