# Generated by Django 3.0 on 2021-03-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210322_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
    ]
