# Generated by Django 3.0 on 2021-03-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_parent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
    ]
