# Generated by Django 3.0 on 2021-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_parent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees_master',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='fees_master',
            name='tutor',
        ),
        migrations.AddField(
            model_name='fees_master',
            name='fees_value',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
