# Generated by Django 3.0 on 2021-03-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_fees_master_tutor_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_master',
            name='fees_value',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
