# Generated by Django 3.0 on 2021-03-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20210323_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_master',
            name='tutor_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
