# Generated by Django 3.0 on 2021-04-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_request',
            name='fees_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Fees_master'),
        ),
    ]
